// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package VerifyDb

import "strconv"

type AnyMessage byte

const (
	AnyMessageNONE       AnyMessage = 0
	AnyMessagePutRequest AnyMessage = 1
	AnyMessagePutReply   AnyMessage = 2
	AnyMessageGetRequest AnyMessage = 3
	AnyMessageGetReply   AnyMessage = 4
)

var EnumNamesAnyMessage = map[AnyMessage]string{
	AnyMessageNONE:       "NONE",
	AnyMessagePutRequest: "PutRequest",
	AnyMessagePutReply:   "PutReply",
	AnyMessageGetRequest: "GetRequest",
	AnyMessageGetReply:   "GetReply",
}

var EnumValuesAnyMessage = map[string]AnyMessage{
	"NONE":       AnyMessageNONE,
	"PutRequest": AnyMessagePutRequest,
	"PutReply":   AnyMessagePutReply,
	"GetRequest": AnyMessageGetRequest,
	"GetReply":   AnyMessageGetReply,
}

func (v AnyMessage) String() string {
	if s, ok := EnumNamesAnyMessage[v]; ok {
		return s
	}
	return "AnyMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
