// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package VerifyDb

import "strconv"

type Conflict int8

const (
	ConflictIgnore  Conflict = 0
	ConflictReplace Conflict = 1
)

var EnumNamesConflict = map[Conflict]string{
	ConflictIgnore:  "Ignore",
	ConflictReplace: "Replace",
}

var EnumValuesConflict = map[string]Conflict{
	"Ignore":  ConflictIgnore,
	"Replace": ConflictReplace,
}

func (v Conflict) String() string {
	if s, ok := EnumNamesConflict[v]; ok {
		return s
	}
	return "Conflict(" + strconv.FormatInt(int64(v), 10) + ")"
}
