// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package VerifyDb

import "strconv"

type Field int8

const (
	FieldUserId     Field = 1
	FieldGeneration Field = 2
	FieldVerify     Field = 3
)

var EnumNamesField = map[Field]string{
	FieldUserId:     "UserId",
	FieldGeneration: "Generation",
	FieldVerify:     "Verify",
}

var EnumValuesField = map[string]Field{
	"UserId":     FieldUserId,
	"Generation": FieldGeneration,
	"Verify":     FieldVerify,
}

func (v Field) String() string {
	if s, ok := EnumNamesField[v]; ok {
		return s
	}
	return "Field(" + strconv.FormatInt(int64(v), 10) + ")"
}
