// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package VerifyDb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsListRequest(buf []byte, offset flatbuffers.UOffsetT) *ListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsListRequest(buf []byte, offset flatbuffers.UOffsetT) *ListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListRequest{}

	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ListRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListRequest) Offset() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ListRequest) MutateOffset(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ListRequest) Limit() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ListRequest) MutateLimit(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func ListRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ListRequestAddOffset(builder *flatbuffers.Builder, offset int32) {
	builder.PrependInt32Slot(0, offset, 0)
}
func ListRequestAddLimit(builder *flatbuffers.Builder, limit int32) {
	builder.PrependInt32Slot(1, limit, 0)
}
func ListRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
